manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mm
      url-base: https://github.com/vrinek/zmk.git
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: masked-mod-morphs-untested
      import: app/west.yml
  self:
    path: config
